# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0002_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.PositiveSmallIntegerField(default=1900),
            preserve_default=False,
        ),
    ]
