# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0003_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.SmallIntegerField(choices=[(0, 'fantasy'), (1, 'fiction'), (2, 'non-fiction')], default=0),
        ),
    ]
