# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0004_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
    ]
