# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mybooks', '0005_book_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('name', 'created'), 'verbose_name': '\u041a\u043d\u0438\u0436\u043a\u0430', 'verbose_name_plural': '\u041a\u043d\u0438\u0436\u043a\u0438'},
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
