# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0006_auto_20180602_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(editable=False),
        ),
    ]
