# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0007_auto_20180602_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(editable=False, verbose_name='\u041e\u043f\u0438\u0441 \u043a\u043d\u0438\u0436\u043a\u0438'),
        ),
    ]
