# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0009_auto_20180602_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
