# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0010_auto_20180602_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
