# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0015_book_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.SmallIntegerField(choices=[(0, 'fantasy'), (1, 'action'), (2, 'adventure'), (3, 'strategy'), (4, 'horror'), (5, 'rpg'), (6, 'sport'), (7, 'shooter')], default=0),
        ),
    ]
