# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0018_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mybooks.Book'),
            preserve_default=False,
        ),
    ]
